import React from 'react';
import {
  mdiAccount,
  mdiAccountCheck,
  mdiAccountCircleOutline,
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiAccountTie,
  mdiAlert,
  mdiAlertCircle,
  mdiAlertOctagon,
  mdiApps,
  mdiArrowDownBold,
  mdiArrowUpBold,
  mdiBackspaceOutline,
  mdiBagChecked,
  mdiBellOffOutline,
  mdiBellOutline,
  mdiBellRingOutline,
  mdiBreadSlice,
  mdiCakeVariant,
  mdiCalendarMonthOutline,
  mdiCard,
  mdiCartOutline,
  mdiCash,
  mdiCashRegister,
  mdiChartBoxOutline,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckDecagram,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClipboardCheckOutline,
  mdiClipboardListOutline,
  mdiClipboardOutline,
  mdiClipboardTextClockOutline,
  mdiClipboardTextOutline,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloudUploadOutline,
  mdiCodeJson,
  mdiCogOutline,
  mdiContentCopy,
  mdiCreditCardOutline,
  mdiCreditCardScanOutline,
  mdiCreditCardSettingsOutline,
  mdiCurrencyInr,
  mdiDatabaseOff,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFilePercentOutline,
  mdiFire,
  mdiFloorPlan,
  mdiFood,
  mdiFoodCroissant,
  mdiFoodForkDrink,
  mdiFoodOff,
  mdiFormatListNumbered,
  mdiGhost,
  mdiGlassCocktail,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiInformation,
  mdiLockOutline,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiMinus,
  mdiNumeric,
  mdiPencil,
  mdiPencilOutline,
  mdiPhoneOutline,
  mdiPlaylistPlus,
  mdiPlus,
  mdiPrinter,
  mdiPrinterOutline,
  mdiPrinterPos,
  mdiQrcode,
  mdiReact,
  mdiReceipt,
  mdiReceiptTextCheckOutline,
  mdiReceiptTextSendOutline,
  mdiShieldLockOutline,
  mdiShopping,
  mdiSilverwareClean,
  mdiSilverwareForkKnife,
  mdiSlide,
  mdiStar,
  mdiTableChair,
  mdiTrashCanOutline,
  mdiTruckDeliveryOutline,
  mdiViewDashboardOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeb,
  mdiWhatsapp,
  mdiWrap,
} from '@mdi/js';
import { View } from 'react-native-web';

export interface MaterialCommunityIconProps {
  name: string;
  size?: number;
  color?: string;
  style?: unknown;
}

const availablePaths: Record<string, string> = {
  account: mdiAccount,
  'account-check': mdiAccountCheck,
  'account-circle-outline': mdiAccountCircleOutline,
  'account-group': mdiAccountGroup,
  'account-group-outline': mdiAccountGroupOutline,
  'account-tie': mdiAccountTie,
  alert: mdiAlert,
  'alert-circle': mdiAlertCircle,
  'alert-octagon': mdiAlertOctagon,
  apps: mdiApps,
  'arrow-down-bold': mdiArrowDownBold,
  'arrow-up-bold': mdiArrowUpBold,
  'backspace-outline': mdiBackspaceOutline,
  'bag-checked': mdiBagChecked,
  'bell-off-outline': mdiBellOffOutline,
  'bell-outline': mdiBellOutline,
  'bell-ring-outline': mdiBellRingOutline,
  'cake-variant': mdiCakeVariant,
  'calendar-month-outline': mdiCalendarMonthOutline,
  card: mdiCard,
  'cart-outline': mdiCartOutline,
  cash: mdiCash,
  'cash-register': mdiCashRegister,
  'chart-box-outline': mdiChartBoxOutline,
  'check-circle': mdiCheckCircle,
  'check-circle-outline': mdiCheckCircleOutline,
  'check-decagram': mdiCheckDecagram,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  'clipboard-check-outline': mdiClipboardCheckOutline,
  'clipboard-list-outline': mdiClipboardListOutline,
  'clipboard-outline': mdiClipboardOutline,
  'clipboard-text-clock-outline': mdiClipboardTextClockOutline,
  'clipboard-text-outline': mdiClipboardTextOutline,
  'clock-outline': mdiClockOutline,
  close: mdiClose,
  'close-circle': mdiCloseCircle,
  'cloud-upload-outline': mdiCloudUploadOutline,
  'code-json': mdiCodeJson,
  'cog-outline': mdiCogOutline,
  'content-copy': mdiContentCopy,
  'credit-card-outline': mdiCreditCardOutline,
  'credit-card-scan-outline': mdiCreditCardScanOutline,
  'credit-card-settings-outline': mdiCreditCardSettingsOutline,
  'currency-inr': mdiCurrencyInr,
  'database-off': mdiDatabaseOff,
  'eye-off-outline': mdiEyeOffOutline,
  'eye-outline': mdiEyeOutline,
  'file-percent-outline': mdiFilePercentOutline,
  fire: mdiFire,
  'floor-plan': mdiFloorPlan,
  food: mdiFood,
  'food-croissant': mdiFoodCroissant,
  'food-fork-drink': mdiFoodForkDrink,
  'food-off': mdiFoodOff,
  'format-list-numbered': mdiFormatListNumbered,
  ghost: mdiGhost,
  'glass-cocktail': mdiGlassCocktail,
  history: mdiHistory,
  information: mdiInformation,
  'lock-outline': mdiLockOutline,
  login: mdiLogin,
  logout: mdiLogout,
  magnify: mdiMagnify,
  menu: mdiMenu,
  minus: mdiMinus,
  numeric: mdiNumeric,
  pencil: mdiPencil,
  'pencil-outline': mdiPencilOutline,
  'phone-outline': mdiPhoneOutline,
  'playlist-plus': mdiPlaylistPlus,
  plus: mdiPlus,
  printer: mdiPrinter,
  'printer-outline': mdiPrinterOutline,
  'printer-pos': mdiPrinterPos,
  qrcode: mdiQrcode,
  react: mdiReact,
  receipt: mdiReceipt,
  'receipt-text-check-outline': mdiReceiptTextCheckOutline,
  'receipt-text-send-outline': mdiReceiptTextSendOutline,
  'shield-lock-outline': mdiShieldLockOutline,
  shopping: mdiShopping,
  'silverware-clean': mdiSilverwareClean,
  'silverware-fork-knife': mdiSilverwareForkKnife,
  slide: mdiSlide,
  star: mdiStar,
  'table-chair': mdiTableChair,
  'trash-can-outline': mdiTrashCanOutline,
  'truck-delivery-outline': mdiTruckDeliveryOutline,
  'view-dashboard-outline': mdiViewDashboardOutline,
  'weather-night': mdiWeatherNight,
  'weather-sunny': mdiWeatherSunny,
  web: mdiWeb,
  whatsapp: mdiWhatsapp,
  wrap: mdiWrap,
  flatbread: mdiBreadSlice,
  'fast-food': mdiFoodForkDrink,
};

const Icon = ({ name, size = 24, color = 'currentColor', style }: MaterialCommunityIconProps) => {
  const iconPath = availablePaths[name] || mdiHelpCircleOutline;

  return (
    <View
      aria-hidden
      style={[
        {
          width: size,
          height: size,
          flexShrink: 0,
          alignItems: 'center',
          justifyContent: 'center',
        },
        style,
      ]}
    >
      <svg width={size} height={size} viewBox="0 0 24 24" focusable="false">
        <path d={iconPath} fill={color} />
      </svg>
    </View>
  );
};

export const MaterialCommunityIcons = Object.assign(Icon, {
  glyphMap: {} as Record<string, number>,
});
